[package]
name = "rbn"
version = "0.1.0"
authors = ["Evan Pratten <ewpratten@gmail.com>"]
edition = "2020"
license-file = "LICENSE"
repository = "https://github.com/Ewpratten/rbn"

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
regex = "1.4.3"
ctrlc = "3.1.7"
pad = "0.1.6"